// AUTO-GENERATED by scripts/classify-urls.mjs and
// scripts/add-legacy-date-redirects.mjs — do not edit by hand.
export interface RedirectEntry { from: string; to: string; }
export const redirects: RedirectEntry[] = [
  {
    "from": "/2007/12/20/free-150-towards-microsoft-adcenter-search-engine-online-ads/",
    "to": "/free-150-towards-microsoft-adcenter-search-engine-online-ads/"
  },
  {
    "from": "/2007/12/20/how-to-submit-a-proposal-to-speak-at-teched-us/",
    "to": "/how-to-submit-a-proposal-to-speak-at-teched-us/"
  },
  {
    "from": "/2007/12/20/intuit-tells-you-to-join-the-entrepreneurial-revolution/",
    "to": "/intuit-tells-you-to-join-the-entrepreneurial-revolution/"
  },
  {
    "from": "/2007/12/20/northwest-arkansas-msdn-express-event-a-success/",
    "to": "/northwest-arkansas-msdn-express-event-a-success/"
  },
  {
    "from": "/2007/12/20/save-50-on-the-microsoft-partner-telesales-service-campaign/",
    "to": "/save-50-on-the-microsoft-partner-telesales-service-campaign/"
  },
  {
    "from": "/2007/12/20/second-shot-program-for-microsoft-certification-exams/",
    "to": "/second-shot-program-for-microsoft-certification-exams/"
  },
  {
    "from": "/2007/12/20/software-developers-beware-of-sales-tax/",
    "to": "/software-developers-beware-of-sales-tax/"
  },
  {
    "from": "/2007/12/20/tulsa-installfest--tons-of-fun/",
    "to": "/tulsa-installfest--tons-of-fun/"
  },
  {
    "from": "/2007/12/20/updated-msdn-flash-features-zain-naboulsi/",
    "to": "/updated-msdn-flash-features-zain-naboulsi/"
  },
  {
    "from": "/2007/12/20/visual-studio-2008-amp-.net-3.5-training-kit/",
    "to": "/visual-studio-2008-amp-.net-3.5-training-kit/"
  },
  {
    "from": "/2007/12/23/go-green-say-no-to-fireplace-and-yes-to-yule/",
    "to": "/go-green-say-no-to-fireplace-and-yes-to-yule/"
  },
  {
    "from": "/2007/12/23/microsofts-download-center-new-beta-uses-silverlight/",
    "to": "/microsofts-download-center-new-beta-uses-silverlight/"
  },
  {
    "from": "/2007/12/26/founder-of-yahoo-groups-dies-in-airplane-crash-in-panama/",
    "to": "/founder-of-yahoo-groups-dies-in-airplane-crash-in-panama/"
  },
  {
    "from": "/2007/12/28/free-amp-discounted-logo-testing-for-windows-server-2008-certifications/",
    "to": "/free-amp-discounted-logo-testing-for-windows-server-2008-certifications/"
  },
  {
    "from": "/2007/12/28/get-2-free-vista-style-icons/",
    "to": "/get-2-free-vista-style-icons/"
  },
  {
    "from": "/2007/12/28/the-newest-geekswithblogs-member-cross-postings-from-www.mysoftwarestartup.com/",
    "to": "/the-newest-geekswithblogs-member-cross-postings-from-www.mysoftwarestartup.com/"
  },
  {
    "from": "/2007/12/28/vb.net-code-example-for-a-sub-main-startup-for-a/",
    "to": "/vb.net-code-example-for-a-sub-main-startup-for-a/"
  },
  {
    "from": "/2007/12/30/community-credit-they-give-stupid-prizes-to-smart-people/",
    "to": "/community-credit-they-give-stupid-prizes-to-smart-people/"
  },
  {
    "from": "/2008/01/01/allstate-kicker-commercial-resembles-our-tech-life/",
    "to": "/allstate-kicker-commercial-resembles-our-tech-life/"
  },
  {
    "from": "/2008/01/02/winner-of-6th-place-at-community-credit.com/",
    "to": "/winner-of-6th-place-at-community-credit.com/"
  },
  {
    "from": "/2008/01/04/awesome-team-development-with-tfs-online-guidebook/",
    "to": "/awesome-team-development-with-tfs-online-guidebook/"
  },
  {
    "from": "/2008/01/10/microsoft-changes-satisfaction-index-in-partner-program/",
    "to": "/microsoft-changes-satisfaction-index-in-partner-program/"
  },
  {
    "from": "/2008/01/14/free-partner-training-windows-server-2008-for-developers/",
    "to": "/free-partner-training-windows-server-2008-for-developers/"
  },
  {
    "from": "/2008/01/15/dallas-techfest-2008/",
    "to": "/dallas-techfest-2008/"
  },
  {
    "from": "/2008/01/15/javier-lozano-amp-spanish-c-compiler/",
    "to": "/javier-lozano-amp-spanish-c-compiler/"
  },
  {
    "from": "/2008/01/15/participating-in-the-we-are-microsoft-event-jan-18-20/",
    "to": "/participating-in-the-we-are-microsoft-event-jan-18-20/"
  },
  {
    "from": "/2008/01/16/scott-guthrie-announces-.net-framework-source-code-availability/",
    "to": "/scott-guthrie-announces-.net-framework-source-code-availability/"
  },
  {
    "from": "/2008/01/16/watch-bill-gates-keynote-at-ces-2008-in-silverlight/",
    "to": "/watch-bill-gates-keynote-at-ces-2008-in-silverlight/"
  },
  {
    "from": "/2008/01/21/we-are-microsoft-2008-event-in-dallas/",
    "to": "/we-are-microsoft-2008-event-in-dallas/"
  },
  {
    "from": "/2008/01/24/autoruns-for-windows-diarrhea-never-felt-so-good/",
    "to": "/autoruns-for-windows-diarrhea-never-felt-so-good/"
  },
  {
    "from": "/2008/01/28/fort-smith-.net-user-group-forming/",
    "to": "/fort-smith-.net-user-group-forming/"
  },
  {
    "from": "/2008/01/28/free-microsoft-webinars-for-partners-ajax-silverlight-exrpression/",
    "to": "/free-microsoft-webinars-for-partners-ajax-silverlight-exrpression/"
  },
  {
    "from": "/2008/01/28/fueling-the-fire-of-recession/",
    "to": "/fueling-the-fire-of-recession/"
  },
  {
    "from": "/2008/01/28/microsoft-small-business-show-amp-silverlight-fakeout/",
    "to": "/microsoft-small-business-show-amp-silverlight-fakeout/"
  },
  {
    "from": "/2008/01/28/more-free-microsoft-partner-training/",
    "to": "/more-free-microsoft-partner-training/"
  },
  {
    "from": "/2008/01/28/msdn-express-event-take-2-feb-27-1-5pm/",
    "to": "/msdn-express-event-take-2-feb-27-1-5pm/"
  },
  {
    "from": "/2008/01/28/partner-program-subsidies---easy-way-to-earn-extra-cash/",
    "to": "/partner-program-subsidies---easy-way-to-earn-extra-cash/"
  },
  {
    "from": "/2008/01/29/american-express-line-of-credit-woes-and-rant/",
    "to": "/american-express-line-of-credit-woes-and-rant/"
  },
  {
    "from": "/2008/02/03/free-source-code-outliner-powertoy-for-visual-studio-2008/",
    "to": "/free-source-code-outliner-powertoy-for-visual-studio-2008/"
  },
  {
    "from": "/2008/02/11/video-of-adding-microsoft-silverlight-to-an-existing-website/",
    "to": "/video-of-adding-microsoft-silverlight-to-an-existing-website/"
  },
  {
    "from": "/2008/02/12/securely-sending-xml-messages-via-digital-signing-in-.net/",
    "to": "/securely-sending-xml-messages-via-digital-signing-in-.net/"
  },
  {
    "from": "/2008/02/13/power-of-social-computing-new-school-viral-vs-old-school/",
    "to": "/power-of-social-computing-new-school-viral-vs-old-school/"
  },
  {
    "from": "/2008/02/16/when-wal-mart-speaks-everyone-listens-the-final-destruction-of/",
    "to": "/when-wal-mart-speaks-everyone-listens-the-final-destruction-of/"
  },
  {
    "from": "/2008/02/21/microsoft-kills-off-adcenter-affiliate-program-paid-referrals-to-their/",
    "to": "/microsoft-kills-off-adcenter-affiliate-program-paid-referrals-to-their/"
  },
  {
    "from": "/2008/02/25/msn-released-i.t.-top-jobs-software-application-developers-ranked/",
    "to": "/msn-released-i.t.-top-jobs-software-application-developers-ranked/"
  },
  {
    "from": "/2008/02/27/heroes-happen-here-official-launch-boasts-silverlight-website/",
    "to": "/heroes-happen-here-official-launch-boasts-silverlight-website/"
  },
  {
    "from": "/2008/02/27/msdn-access-changed-for-microsoft-partners/",
    "to": "/msdn-access-changed-for-microsoft-partners/"
  },
  {
    "from": "/2008/02/27/upcoming-march-speaking-events-sql-server-reporting-services/",
    "to": "/upcoming-march-speaking-events-sql-server-reporting-services/"
  },
  {
    "from": "/2008/03/04/first-fort-smith-.net-user-group-meeting/",
    "to": "/first-fort-smith-.net-user-group-meeting/"
  },
  {
    "from": "/2008/03/05/sql-server-management-pack/",
    "to": "/sql-server-management-pack/"
  },
  {
    "from": "/2008/03/06/free-devexpress-.net-controls/",
    "to": "/free-devexpress-.net-controls/"
  },
  {
    "from": "/2008/03/11/pictures-of-the-1st-fort-smith-.net-user-group-meeting/",
    "to": "/pictures-of-the-1st-fort-smith-.net-user-group-meeting/"
  },
  {
    "from": "/2008/03/11/state-government-kudos/",
    "to": "/state-government-kudos/"
  },
  {
    "from": "/2008/03/22/getting-more-out-of-sql-server-reporting-services-charts/",
    "to": "/getting-more-out-of-sql-server-reporting-services-charts/"
  },
  {
    "from": "/2008/03/22/join-the-microsoft-game-studios-beta-program/",
    "to": "/join-the-microsoft-game-studios-beta-program/"
  },
  {
    "from": "/2008/03/22/sql-injection-article/",
    "to": "/sql-injection-article/"
  },
  {
    "from": "/2008/03/22/sql-server-reporting-services-licensing-info/",
    "to": "/sql-server-reporting-services-licensing-info/"
  },
  {
    "from": "/2008/03/22/to-bug-the-microsoft-msdn-evangelist-or-not-to-bug/",
    "to": "/to-bug-the-microsoft-msdn-evangelist-or-not-to-bug/"
  },
  {
    "from": "/2008/03/26/preferred-method-for-read-only-config-files/",
    "to": "/preferred-method-for-read-only-config-files/"
  },
  {
    "from": "/2008/04/06/received-microsoft-mvp-award/",
    "to": "/received-microsoft-mvp-award/"
  },
  {
    "from": "/2008/05/09/northwest-arkansas-sql-server-user-group-1st-meeting/",
    "to": "/northwest-arkansas-sql-server-user-group-1st-meeting/"
  },
  {
    "from": "/2008/05/19/20-business-tips-from-intuit-quickbooks/",
    "to": "/20-business-tips-from-intuit-quickbooks/"
  },
  {
    "from": "/2008/05/19/microsoft-adcenter-needs-a-workshop/",
    "to": "/microsoft-adcenter-needs-a-workshop/"
  },
  {
    "from": "/2008/06/04/tell-internet-explorer-8-beta-to-show-your-site-properly/",
    "to": "/tell-internet-explorer-8-beta-to-show-your-site-properly/"
  },
  {
    "from": "/2008/06/05/go-visit-the-visual-basic-product-team-at-teched/",
    "to": "/go-visit-the-visual-basic-product-team-at-teched/"
  },
  {
    "from": "/2008/06/05/mvp-summit-being-busy-plus-presenting-the-little-rock/",
    "to": "/mvp-summit-being-busy-plus-presenting-the-little-rock/"
  },
  {
    "from": "/2008/06/05/writing-to-.net-config-files/",
    "to": "/writing-to-.net-config-files/"
  },
  {
    "from": "/2008/06/09/congratulations-amp-thanks-to-jay-smith-amp-michael-paladino/",
    "to": "/congratulations-amp-thanks-to-jay-smith-amp-michael-paladino/"
  },
  {
    "from": "/2008/06/15/growing-your-software-business-stuck-in-a-rut/",
    "to": "/growing-your-software-business-stuck-in-a-rut/"
  },
  {
    "from": "/2008/06/17/microsoft-certification-exam-voucher-giveaway/",
    "to": "/microsoft-certification-exam-voucher-giveaway/"
  },
  {
    "from": "/2008/06/19/regex-tools-for-visual-studio-amp-the-social-web/",
    "to": "/regex-tools-for-visual-studio-amp-the-social-web/"
  },
  {
    "from": "/2008/07/04/nbc-olympics-site-goes-live-with-silverlight-2-streaming/",
    "to": "/nbc-olympics-site-goes-live-with-silverlight-2-streaming/"
  },
  {
    "from": "/2008/07/08/winner-of-certification-exam-voucher/",
    "to": "/winner-of-certification-exam-voucher/"
  },
  {
    "from": "/2008/07/10/how-i-think-twitter-can-solve-its-problems/",
    "to": "/how-i-think-twitter-can-solve-its-problems/"
  },
  {
    "from": "/2008/07/21/microsoft-congregates-its-ads-under-one-flag-quotmicrosoft-advertisingquot/",
    "to": "/microsoft-congregates-its-ads-under-one-flag-quotmicrosoft-advertisingquot/"
  },
  {
    "from": "/2008/07/30/nashville-devlink-conference-sold-out/",
    "to": "/nashville-devlink-conference-sold-out/"
  },
  {
    "from": "/2008/07/31/chris-williams-9-questions/",
    "to": "/chris-williams-9-questions/"
  },
  {
    "from": "/2008/08/07/speaking-at-nashville-devlink/",
    "to": "/speaking-at-nashville-devlink/"
  },
  {
    "from": "/2008/08/11/jeffrey-palermo-set-to-speak-thursday-in-northwest-arkansas/",
    "to": "/jeffrey-palermo-set-to-speak-thursday-in-northwest-arkansas/"
  },
  {
    "from": "/2008/08/24/devlink-presentation-files-discount-codes-amp-links/",
    "to": "/devlink-presentation-files-discount-codes-amp-links/"
  },
  {
    "from": "/2008/09/01/nashville-devlink-recap/",
    "to": "/nashville-devlink-recap/"
  },
  {
    "from": "/2008/09/16/child-labor-india-soccer-balls-amp-walmart/",
    "to": "/child-labor-india-soccer-balls-amp-walmart/"
  },
  {
    "from": "/2008/09/20/jonesboro-amp-harrison-are-getting-.net-user-groups/",
    "to": "/jonesboro-amp-harrison-are-getting-.net-user-groups/"
  },
  {
    "from": "/2008/09/20/memphis-.net-user-group-visit-sept-25th/",
    "to": "/memphis-.net-user-group-visit-sept-25th/"
  },
  {
    "from": "/2008/09/22/come-catch-me-at-tulsa-techfest-2008-oct-9-10th/",
    "to": "/come-catch-me-at-tulsa-techfest-2008-oct-9-10th/"
  },
  {
    "from": "/2008/09/23/inaugural-harrison-.net-user-group-meeting-oct-21st-2008/",
    "to": "/inaugural-harrison-.net-user-group-meeting-oct-21st-2008/"
  },
  {
    "from": "/2008/10/28/letter-from-steve-ballmer-ceo-microsoft/",
    "to": "/letter-from-steve-ballmer-ceo-microsoft/"
  },
  {
    "from": "/2008/10/29/wishing-you-were-at-pdc-we-saved-the-jacksons-amp/",
    "to": "/wishing-you-were-at-pdc-we-saved-the-jacksons-amp/"
  },
  {
    "from": "/2008/11/21/microsoft-bizspark-for-technology-startups/",
    "to": "/microsoft-bizspark-for-technology-startups/"
  },
  {
    "from": "/2008/11/21/microsoft-no-longer-marketing-windows-live-onecare/",
    "to": "/microsoft-no-longer-marketing-windows-live-onecare/"
  },
  {
    "from": "/2009/01/22/upcoming-developer-events/",
    "to": "/upcoming-developer-events/"
  },
  {
    "from": "/2009/02/03/ineta-community-champion-awardee/",
    "to": "/ineta-community-champion-awardee/"
  },
  {
    "from": "/2009/02/15/congratulations-amp-thanks-to-scott-spradlin/",
    "to": "/congratulations-amp-thanks-to-scott-spradlin/"
  },
  {
    "from": "/2009/03/09/northwest-arkansas-technology-council-inaugural-meeting-2009-03-10/",
    "to": "/northwest-arkansas-technology-council-inaugural-meeting-2009-03-10/"
  },
  {
    "from": "/2009/03/16/ozarks-.net-user-group-ndash-claudio-lassala-laptop-giveaway/",
    "to": "/ozarks-.net-user-group-ndash-claudio-lassala-laptop-giveaway/"
  },
  {
    "from": "/2009/03/20/ineta-board-of-directors-appointment/",
    "to": "/ineta-board-of-directors-appointment/"
  },
  {
    "from": "/2009/03/20/new-fedex-ssl-cert-is-bound-to-cause-problems/",
    "to": "/new-fedex-ssl-cert-is-bound-to-cause-problems/"
  },
  {
    "from": "/2009/03/31/ineta-board-of-directors-conference-call/",
    "to": "/ineta-board-of-directors-conference-call/"
  },
  {
    "from": "/2009/04/24/a-proud-influencer-irsquom-giving-a-10k-prize-giveaway/",
    "to": "/a-proud-influencer-irsquom-giving-a-10k-prize-giveaway/"
  },
  {
    "from": "/2009/08/06/ineta-speakers-bureau-update/",
    "to": "/ineta-speakers-bureau-update/"
  },
  {
    "from": "/2009/09/29/steve-ballmerrsquos-recent-ceo-letter-ndash-do-more-with-less/",
    "to": "/steve-ballmerrsquos-recent-ceo-letter-ndash-do-more-with-less/"
  },
  {
    "from": "/2010/03/25/take-advantage-of-the-stimulus-plan-by-hiring-someone/",
    "to": "/take-advantage-of-the-stimulus-plan-by-hiring-someone/"
  },
  {
    "from": "/2010/03/26/free-codesmith-license/",
    "to": "/free-codesmith-license/"
  },
  {
    "from": "/2010/04/03/i-still-think-twitter-is-dead-hellip-but/",
    "to": "/i-still-think-twitter-is-dead-hellip-but/"
  },
  {
    "from": "/2010/04/18/bulgogi-to-beignets/",
    "to": "/bulgogi-to-beignets/"
  },
  {
    "from": "/2010/04/21/microsoft-2010-product-tour/",
    "to": "/microsoft-2010-product-tour/"
  },
  {
    "from": "/2010/04/21/retail-link-data-storage-requirements/",
    "to": "/retail-link-data-storage-requirements/"
  },
  {
    "from": "/2010/05/03/how-resharper-saved-the-day/",
    "to": "/how-resharper-saved-the-day/"
  },
  {
    "from": "/2010/05/05/inexpensive-business-checks/",
    "to": "/inexpensive-business-checks/"
  },
  {
    "from": "/2010/05/10/windows-installer-ndash-installaware-coupon/",
    "to": "/windows-installer-ndash-installaware-coupon/"
  },
  {
    "from": "/2010/05/18/microsoftrsquos-new-technical-computing-initiative/",
    "to": "/microsoftrsquos-new-technical-computing-initiative/"
  },
  {
    "from": "/2010/07/29/antitrust-lawsuit-versus-megagiant-oclc/",
    "to": "/antitrust-lawsuit-versus-megagiant-oclc/"
  },
  {
    "from": "/2010/08/03/microsoft-lightswitch/",
    "to": "/microsoft-lightswitch/"
  },
  {
    "from": "/2010/08/17/fun-amp-gamesndashmicrosoftrsquos-new-aoe-online/",
    "to": "/fun-amp-gamesndashmicrosoftrsquos-new-aoe-online/"
  },
  {
    "from": "/2013/01/30/mvp-summit-here-we-come/",
    "to": "/mvp-summit-here-we-come/"
  },
  {
    "from": "/2013/03/10/152363/",
    "to": "/152363/"
  },
  {
    "from": "/2013/04/06/microsoft-mvp-award-again/",
    "to": "/microsoft-mvp-award-again/"
  },
  {
    "from": "/2013/08/18/paypass-and-nfc-payments-with-windows-8-phones/",
    "to": "/paypass-and-nfc-payments-with-windows-8-phones/"
  },
  {
    "from": "/2016/10/17/updated-blog/",
    "to": "/updated-blog/"
  },
  {
    "from": "/2016/12/02/continuous-integration-with-vsts-tips-1-2/",
    "to": "/continuous-integration-with-vsts-tips-1-2/"
  },
  {
    "from": "/2016/12/02/continuous-integration-with-vsts1/",
    "to": "/continuous-integration-with-vsts1/"
  },
  {
    "from": "/2016/12/19/use-vs-code-to-create-powershell-scripts-to-move-files-into-folders-by-date/",
    "to": "/use-vs-code-to-create-powershell-scripts-to-move-files-into-folders-by-date/"
  },
  {
    "from": "/2017/02/08/spam-domains/",
    "to": "/spam-domains/"
  },
  {
    "from": "/2017/02/13/dax-calculation-for-local-time-versus-utc/",
    "to": "/dax-calculation-for-local-time-versus-utc/"
  },
  {
    "from": "/2017/02/22/power-pivot-power-bi-training-in-bentonville-at-walmart-intl-building/",
    "to": "/power-pivot-power-bi-training-in-bentonville-at-walmart-intl-building/"
  },
  {
    "from": "/2017/03/14/performance-tuning-in-azure-sql-data-warehouse/",
    "to": "/performance-tuning-in-azure-sql-data-warehouse/"
  },
  {
    "from": "/2017/04/26/vsts-with-code-signed-pfx-certificates/",
    "to": "/vsts-with-code-signed-pfx-certificates/"
  },
  {
    "from": "/2018/02/15/blogging-again/",
    "to": "/blogging-again/"
  },
  {
    "from": "/2018/02/16/cloudxplorer-discount/",
    "to": "/cloudxplorer-discount/"
  },
  {
    "from": "/2019/02/15/blogging-again/",
    "to": "/blogging-again/"
  },
  {
    "from": "/2020/02/16/cloudxplorer-discount/",
    "to": "/cloudxplorer-discount/"
  },
  {
    "from": "/blog/page3/",
    "to": "/blog/"
  },
  {
    "from": "/blogs/boxed-classic-sidebar/page/11/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-classic-sidebar/page/17/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-classic/page/16/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-classic/page/2/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/14/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/16/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/7/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/13/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/2/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/3/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/9/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/10/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/14/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/7/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/9/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid/page/15/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/12/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/18/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/20/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/4/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/classic/page/19/",
    "to": "/"
  },
  {
    "from": "/blogs/classic/page/3/",
    "to": "/"
  },
  {
    "from": "/blogs/page/14/",
    "to": "/"
  },
  {
    "from": "/blogs/page/7/",
    "to": "/"
  },
  {
    "from": "/blogs/page/8/",
    "to": "/"
  },
  {
    "from": "/contact/contact-1/",
    "to": "/"
  },
  {
    "from": "/contact/contact-3/",
    "to": "/"
  },
  {
    "from": "/elements/animated_text/",
    "to": "/"
  },
  {
    "from": "/elements/image_hover/",
    "to": "/"
  },
  {
    "from": "/elements/pricing/",
    "to": "/"
  },
  {
    "from": "/elements/tables/",
    "to": "/"
  },
  {
    "from": "/elements/typography/",
    "to": "/"
  },
  {
    "from": "/elements/video_popup/",
    "to": "/"
  },
  {
    "from": "/features/footer3/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-12/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-18/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-21/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-22/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-3/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-8/",
    "to": "/"
  },
  {
    "from": "/portfolio/architectural-photography/",
    "to": "/"
  },
  {
    "from": "/portfolio/brand-identity/",
    "to": "/"
  },
  {
    "from": "/portfolio/commercial-photography/",
    "to": "/"
  },
  {
    "from": "/portfolio/digital-photo/",
    "to": "/"
  },
  {
    "from": "/portfolio/environmental-design/",
    "to": "/"
  },
  {
    "from": "/portfolio/experimental-typography/",
    "to": "/"
  },
  {
    "from": "/portfolio/interactive-design/",
    "to": "/"
  },
  {
    "from": "/portfolio/mobile-app-design/",
    "to": "/"
  },
  {
    "from": "/portfolios/grid-portfolio/",
    "to": "/"
  },
  {
    "from": "/portfolios/masonry-portfolio-details/",
    "to": "/"
  },
  {
    "from": "/posts/when-the-recruiter-becomes-the-bottleneck/",
    "to": "/when-the-recruiter-becomes-the-bottleneck/"
  },
  {
    "from": "/randy-walker/",
    "to": "/about/"
  },
  {
    "from": "/services/index-3/",
    "to": "/"
  },
  {
    "from": "/shop/",
    "to": "/"
  },
  {
    "from": "/shop/featured/featured_product3/",
    "to": "/"
  },
  {
    "from": "/tag/RegEx/",
    "to": "/tag/regex/"
  },
  {
    "from": "/tags/",
    "to": "/"
  }
];
