// AUTO-GENERATED by scripts/classify-urls.mjs — do not edit by hand.
// Generated from tsk-indexed-urls.csv classification.
export interface RedirectEntry { from: string; to: string; }
export const redirects: RedirectEntry[] = [
  {
    "from": "/2008/01/15/javier-lozano-amp-spanish-c-compiler/",
    "to": "/javier-lozano-amp-spanish-c-compiler/"
  },
  {
    "from": "/2008/01/16/watch-bill-gates-keynote-at-ces-2008-in-silverlight/",
    "to": "/watch-bill-gates-keynote-at-ces-2008-in-silverlight/"
  },
  {
    "from": "/2008/01/21/we-are-microsoft-2008-event-in-dallas/",
    "to": "/we-are-microsoft-2008-event-in-dallas/"
  },
  {
    "from": "/2008/01/28/fort-smith-.net-user-group-forming/",
    "to": "/fort-smith-.net-user-group-forming/"
  },
  {
    "from": "/2008/02/03/free-source-code-outliner-powertoy-for-visual-studio-2008/",
    "to": "/free-source-code-outliner-powertoy-for-visual-studio-2008/"
  },
  {
    "from": "/2008/02/27/heroes-happen-here-official-launch-boasts-silverlight-website/",
    "to": "/heroes-happen-here-official-launch-boasts-silverlight-website/"
  },
  {
    "from": "/2008/03/04/first-fort-smith-.net-user-group-meeting/",
    "to": "/first-fort-smith-.net-user-group-meeting/"
  },
  {
    "from": "/2008/03/05/sql-server-management-pack/",
    "to": "/sql-server-management-pack/"
  },
  {
    "from": "/2008/03/06/free-devexpress-.net-controls/",
    "to": "/free-devexpress-.net-controls/"
  },
  {
    "from": "/2008/03/26/preferred-method-for-read-only-config-files/",
    "to": "/preferred-method-for-read-only-config-files/"
  },
  {
    "from": "/2008/05/09/my-mariah-carey-geek-rant/",
    "to": "/my-mariah-carey-geek-rant/"
  },
  {
    "from": "/2008/05/09/northwest-arkansas-sql-server-user-group-1st-meeting/",
    "to": "/northwest-arkansas-sql-server-user-group-1st-meeting/"
  },
  {
    "from": "/2008/06/04/tell-internet-explorer-8-beta-to-show-your-site-properly/",
    "to": "/tell-internet-explorer-8-beta-to-show-your-site-properly/"
  },
  {
    "from": "/2008/06/17/microsoft-certification-exam-voucher-giveaway/",
    "to": "/microsoft-certification-exam-voucher-giveaway/"
  },
  {
    "from": "/2008/07/04/nbc-olympics-site-goes-live-with-silverlight-2-streaming/",
    "to": "/nbc-olympics-site-goes-live-with-silverlight-2-streaming/"
  },
  {
    "from": "/2008/07/10/using-jott-for-child-custody-records/",
    "to": "/using-jott-for-child-custody-records/"
  },
  {
    "from": "/2008/08/07/steven-curtis-chapman-shares-as-do-i/",
    "to": "/steven-curtis-chapman-shares-as-do-i/"
  },
  {
    "from": "/2009/03/31/ineta-board-of-directors-conference-call/",
    "to": "/ineta-board-of-directors-conference-call/"
  },
  {
    "from": "/2010/07/29/antitrust-lawsuit-versus-megagiant-oclc/",
    "to": "/antitrust-lawsuit-versus-megagiant-oclc/"
  },
  {
    "from": "/2010/08/17/fun-amp-gamesndashmicrosoftrsquos-new-aoe-online/",
    "to": "/fun-amp-gamesndashmicrosoftrsquos-new-aoe-online/"
  },
  {
    "from": "/2017/02/22/power-pivot-power-bi-training-in-bentonville-at-walmart-intl-building/",
    "to": "/power-pivot-power-bi-training-in-bentonville-at-walmart-intl-building/"
  },
  {
    "from": "/2017/03/14/performance-tuning-in-azure-sql-data-warehouse/",
    "to": "/performance-tuning-in-azure-sql-data-warehouse/"
  },
  {
    "from": "/2017/04/26/vsts-with-code-signed-pfx-certificates/",
    "to": "/vsts-with-code-signed-pfx-certificates/"
  },
  {
    "from": "/2018/02/15/blogging-again/",
    "to": "/blogging-again/"
  },
  {
    "from": "/2018/02/16/cloudxplorer-discount/",
    "to": "/cloudxplorer-discount/"
  },
  {
    "from": "/blogs/boxed-classic-sidebar/page/11/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-classic-sidebar/page/17/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-classic/page/16/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-classic/page/2/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/14/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/16/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid-sidebar/page/7/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/13/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/2/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/3/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/boxed-grid/page/9/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/10/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/14/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/7/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid-sidebar/page/9/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid/page/15/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-grid/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/12/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/18/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/20/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/4/",
    "to": "/"
  },
  {
    "from": "/blogs/classic-sidebar/page/6/",
    "to": "/"
  },
  {
    "from": "/blogs/classic/page/19/",
    "to": "/"
  },
  {
    "from": "/blogs/classic/page/3/",
    "to": "/"
  },
  {
    "from": "/blogs/page/14/",
    "to": "/"
  },
  {
    "from": "/blogs/page/7/",
    "to": "/"
  },
  {
    "from": "/blogs/page/8/",
    "to": "/"
  },
  {
    "from": "/contact/contact-1/",
    "to": "/"
  },
  {
    "from": "/contact/contact-3/",
    "to": "/"
  },
  {
    "from": "/elements/animated_text/",
    "to": "/"
  },
  {
    "from": "/elements/image_hover/",
    "to": "/"
  },
  {
    "from": "/elements/pricing/",
    "to": "/"
  },
  {
    "from": "/elements/tables/",
    "to": "/"
  },
  {
    "from": "/elements/typography/",
    "to": "/"
  },
  {
    "from": "/elements/video_popup/",
    "to": "/"
  },
  {
    "from": "/features/footer3/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-18/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-21/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-22/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-3/",
    "to": "/"
  },
  {
    "from": "/home-pages/index-8/",
    "to": "/"
  },
  {
    "from": "/portfolio/architectural-photography/",
    "to": "/"
  },
  {
    "from": "/portfolio/brand-identity/",
    "to": "/"
  },
  {
    "from": "/portfolio/commercial-photography/",
    "to": "/"
  },
  {
    "from": "/portfolio/digital-photo/",
    "to": "/"
  },
  {
    "from": "/portfolio/environmental-design/",
    "to": "/"
  },
  {
    "from": "/portfolio/experimental-typography/",
    "to": "/"
  },
  {
    "from": "/portfolio/interactive-design/",
    "to": "/"
  },
  {
    "from": "/portfolio/mobile-app-design/",
    "to": "/"
  },
  {
    "from": "/portfolios/grid-portfolio/",
    "to": "/"
  },
  {
    "from": "/portfolios/masonry-portfolio-details/",
    "to": "/"
  },
  {
    "from": "/services/index-3/",
    "to": "/"
  },
  {
    "from": "/shop/",
    "to": "/"
  },
  {
    "from": "/shop/featured/featured_product3/",
    "to": "/"
  },
  {
    "from": "/tag/bill-gates/",
    "to": "/"
  },
  {
    "from": "/tag/internet-explorer/",
    "to": "/"
  },
  {
    "from": "/tag/microsoft-tools/",
    "to": "/"
  },
  {
    "from": "/tag/social-computing/",
    "to": "/"
  },
  {
    "from": "/tag/visual-basic/",
    "to": "/"
  },
  {
    "from": "/tags/",
    "to": "/"
  }
];
